[gcp_service_account]
type = "service_account"
project_id = "nth-passage-394008"
private_key_id = "794308977d5f76974742a87092e50d1b80947a75"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCn5e6JqNRxc9qJ
jsPyqKWuCmWcI/RAtJ8kVTvDnDRsbLtjKti23KWIMZLIU+X4aAHRFIVRYT2Pv0zg
guVxuvD+lOV56NOiIVr+RrZ69zfGMp6ixY7Za8mEXeeWI4oclFIy2yDk7P1kCDi4
0MGtOlnh8T3SCwK/Fmqg5BKZlhwX1G0+HvKbI3bKSf541Eccy2QzJw9zI2nlY3MN
rMAnxtIcw5zvo+bp5q1am5mi1OJ4dV/B+sL+JhKBhlUxQiz0AWjMNmIqjcqNrQnh
BN/N+6Z7cHuZ2+e7Cn3ZoIrid+o5RSfRgeJz6Ul1XNcxUPN56myZ0xCaq5HP4mAk
gCUA3JKNAgMBAAECggEAJaTyFL9b0owtRYZS/Mc/ToRaP+X3z8IvpE/P9I3DW0QN
x7BFospZ+u1SgcP93fJD5gL52UM6ME6uB/CRTSyi+BGeWfUP7lwYMMbeBzgCs1eK
JeixnKIELr93OzyArOO8glaLS4ivT4xgW1/C7PoWSQhz2fJKDVoTUjuQyArWBaln
vZM4STZwsMx99m8wrU1U95c8lz7VsfkFcDwFOZqHpdtaAcEr9uDbf/F13SrleLZp
cnSsRr6IJ0lvCNLoWTchCfJ7iDM6Q0NQBx/PGbayenXyGWph+DApQXXj7tBUZQPp
SQvaxIGPE4bZv/7aa8aGrvKhIXzQS91xf0X5nKnWQQKBgQDoFA1lx+jmNudD4BOb
lLbmdYTSZ1NmtgEI5JFFnpqJStUul23CrHfUJQxKd5W0Ei7MsvnSXaSR/wwXYkBs
i0JhhSkC3Abey/31zhFU6Tb38R5fAVmbkWZnQyxL4ZnCAmD5dIRBvwnqJt2sUVw2
q1bwkTa8OqMqf5pYS064uf60tQKBgQC5NFSye+53gE4oVvJfkA8nw5+WTvedJbhZ
ww7oyg6cOu8qRlDfNnwVKXyrxhS63PT3dt87nyru+AOXbF0yc7JFYsvowUpajWzR
M1ML5R7JEkZ2yJXkAOfnluwEGsCff1O2RgsdndW6TPcCVhoeOGGdUafua0nYO09K
Exz9Jc8leQKBgBsTa9S6FAP319dlZyQ5n3UXtN1PTL2o8kn1ULWMoX7vChwbcqTJ
tlk70UlG1mJh1K/xGZBfeHnIBcMcpWOEg8QY4wYAYZTQu9pXplH/u3gF24M+BxRN
TGMzxRE9StEFsgaof12kSiXVTvtxqo5+QvBiIL6pIKwuovU2JAMNQBgZAoGAZWO2
sneSVy2QnBjtW0+cXGKF7V2RxSAvSkS01tA3K2RAJl6US36ic1tg+xDXrGzmVstm
7lb2xBhWrwEODF62S7IIe4XF1Mjzt5tnbW2jauRsWv74v/eW/Xvr/Vs/9JFaHME/
uJj9tp4H4+mLJtwq5FsdmjJ2HMBradwI1LVsL9ECgYEAxAQXUrihHxAdOAS6Tyrj
yMMHCwOGLhCiM1IxejqSDtSgpmRgda8gNrKXwjw0uOiSqudc8KpHcotKo35N4MSL
Onq7/RH4s5GK4PVkcfLcNlW6o2udtKe9n4M+KMRnjqdyUsLPdNCindtZVajL1EB1
8zeUcPSnG4FGLLnZxYqMNWk=
-----END PRIVATE KEY-----
"""
client_email = "service-trial@nth-passage-394008.iam.gserviceaccount.com"
client_id = "111694399487933915006"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-trial%40nth-passage-394008.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
